quickreference: fix unmatched XML tag in Norwegian translation.
Not sure why the first build worked, but subsequent builds failed (maybe
there is something wrong with the order of actions?). In any case, the
build fails with:

> xml/gimp-keys-nn.xml:2: parser error : Start tag expected, '<' not found

And the reason is because the XML actually starts with an error message
instead of the usual <?xml?> header:

========================
Source xml: /home/jehan/dev/src/gimp-help/quickreference/gimp-keys.xml
Source po : /home/jehan/dev/src/gimp-help/quickreference/po/nn.po

Translated msgstr:
Du kan også aktivere menyane ved å halde nede <Alt>-tasten samstundes som du trykker den bokstaven som er understreka i menynamnet.

ERROR: Found unmatched tags in po msgstr.
Tags not matched: ['Alt']
========================

Since the translated content indeed expects possible XML tags,
translators should not use < and > randomly.
Moreover I tested <alt/> as it is used in other places, but the
generated SVG does not display the Alt key image, so I guess this tag
only works in specific fields. Anyway since the source was not using an
XML tag either, let's just stick to simply writing Alt normally.