Fixes XML compilation error for `sl`
This patches an error and failure compiling XML:

    po/sl/menus/colors/components.po:302: 'msgid' and 'msgstr' entries
    do not both end with '\n'

I've left the pair as fuzzy, since I know nothing of the slovenian
translation for HSL.